export const SETUSERID = "SETUSERID";
export const SETALBUMID = "SETALBUMID";
export const SETADDBUTTON = "SETADDBUTTON";
export const SETLOGOUTBUTTON = "SETLOGOUTBUTTON";
export const SETTODOS = "SETTODOS";
export const APPENDTODO = "APPENDTODOS";
export const SETSIDEBAR = "SETSIDEBAR";
export const SETMENU = "SETMENU";
